### ISSUE TITLE
Wrong URL for new consul binaries

### ISSUE THREAD

**Issue by brahama** [hypoport/consul-rpm-rhel6#1]
Hi guyys,

Trying to use it for centos 6 and new versions of consul and didnt work. The problem is the URL it rries to fetch the binary from.

Just with this changes it worked :)

diff build-consul-rpm.sh build-consul-rpm.sh.orig 

```
22c22
<        ZIP=consul_${VERSION}_linux_amd64.zip
---
>        ZIP=${VERSION}_linux_amd64.zip
30,31c30
< #URL="https://dl.bintray.com/mitchellh/consul/${ZIP}"
< URL="https://releases.hashicorp.com/consul/${VERSION}/${ZIP}"
---
> URL="https://dl.bintray.com/mitchellh/consul/${ZIP}"
```

Cheers

**Comment by JoergM** [comment]
Thanks! I have updated the scripts.
